apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SparebankenVest/public-helm-charts.git
    targetRevision: HEAD
    path: stable/akv2k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: akv2k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
