apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
#  project: infra-apps
  source:
    path: stable/akv2k8s
    repoURL: https://github.com/SparebankenVest/public-helm-charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
